import { expect, test } from 'vitest';
import { solve } from '.';

const useCases = [
  {
    text: `{"Student":{"Name":"John","Age":"15"},"Class":"10"}`,
    noOfQueries: 3,
    queries: ['Student.Name', 'Student.Age', 'Class'],
    output: 'John,15,10',
  },
  {
    text: `{"m":{"stx":"fb","c":{"bdo":{"a":{"trp":"wvt","tijb":"z","nggc":{"urd":"dkq"},"qm":{"tqo":"k","eub":"dehi"},"vsk":{"xlz":"qmw","a":"uer","bn":"k","jaep":"rre"}},"k":{"fz":{"te":"iyb","lu":"ajd","d":"v","zclhy":"pz","cpc":"jyi"},"lpwu":"fuk","h":"y","kql":{"m":"qbn"},"u":{"zl":"jtb"}}},"xmi":{"xizo":{"mx":"kozp"}},"zpq":{"v":"cjkgt","j":{"abv":{"gkml":"w","hcjgq":"anr","vzfu":"hyz","nz":"aws"},"ij":"t","jbf":{"wd":"en","cb":"jgj"},"n":"iatlx","kad":"q"},"xiy":{"ywy":"z"},"lnzcj":"hx","n":"d"}},"dj":{"pn":{"x":"ynekz","al":"fvj","zfhy":{"wo":"icot","qfds":{"dxq":"tswy"},"t":{"ab":"kr","qkg":"jn","zc":"dxh","rkh":"mjo","cjb":"yaq"}},"jq":"a"},"nz":{"ls":{"wlgi":"ctm","bt":"qfat","a":{"dgv":"fspq"}},"iix":"gmah"}},"ver":{"xkago":"f"},"rvoi":"ram"}}`,
    noOfQueries: 49,
    queries: [
      'm.c.bdo.a.nggc.urd',
      'm.c.bdo.a.qm.eub',
      'm.c.bdo.a.qm.tqo',
      'm.c.bdo.a.tijb',
      'm.c.bdo.a.trp',
      'm.c.bdo.a.vsk.a',
      'm.c.bdo.a.vsk.bn',
      'm.c.bdo.a.vsk.jaep',
      'm.c.bdo.a.vsk.xlz',
      'm.c.bdo.k.fz.cpc',
      'm.c.bdo.k.fz.d',
      'm.c.bdo.k.fz.lu',
      'm.c.bdo.k.fz.te',
      'm.c.bdo.k.fz.zclhy',
      'm.c.bdo.k.h',
      'm.c.bdo.k.kql.m',
      'm.c.bdo.k.lpwu',
      'm.c.bdo.k.u.zl',
      'm.c.xmi.xizo.mx',
      'm.c.zpq.j.abv.gkml',
      'm.c.zpq.j.abv.hcjgq',
      'm.c.zpq.j.abv.nz',
      'm.c.zpq.j.abv.vzfu',
      'm.c.zpq.j.ij',
      'm.c.zpq.j.jbf.cb',
      'm.c.zpq.j.jbf.wd',
      'm.c.zpq.j.kad',
      'm.c.zpq.j.n',
      'm.c.zpq.lnzcj',
      'm.c.zpq.n',
      'm.c.zpq.v',
      'm.c.zpq.xiy.ywy',
      'm.dj.nz.iix',
      'm.dj.nz.ls.a.dgv',
      'm.dj.nz.ls.bt',
      'm.dj.nz.ls.wlgi',
      'm.dj.pn.al',
      'm.dj.pn.jq',
      'm.dj.pn.x',
      'm.dj.pn.zfhy.qfds.dxq',
      'm.dj.pn.zfhy.t.ab',
      'm.dj.pn.zfhy.t.cjb',
      'm.dj.pn.zfhy.t.qkg',
      'm.dj.pn.zfhy.t.rkh',
      'm.dj.pn.zfhy.t.zc',
      'm.dj.pn.zfhy.wo',
      'm.rvoi',
      'm.stx',
      'm.ver.xkago',
    ],
    output:
      'dkq,dehi,k,z,wvt,uer,k,rre,qmw,jyi,v,ajd,iyb,pz,y,qbn,fuk,jtb,kozp,w,anr,aws,hyz,t,jgj,en,q,iatlx,hx,d,cjkgt,z,gmah,fspq,qfat,ctm,fvj,a,ynekz,tswy,kr,yaq,jn,mjo,dxh,icot,ram,fb,f',
  },
  {
    text: `{"y":{"gl":{"unjv":{"vv":{"vre":{"kefi":"ljxc","y":"jwewp","hx":"lng"},"khhe":"gfx","u":{"mito":"nh","nly":"przd","jtn":"gfze"},"vu":{"loz":"xpwdd","cz":"hp","ebvm":"e"}},"azn":{"ckt":"oft"},"flv":"c","phgv":{"dpqv":"luh","jkw":{"gq":"ivx","b":"qzv","hwuf":"xrnif"}},"b":{"dxuy":"rwn","gz":{"qz":"cp","kss":"jxwi","vv":"osos","ayo":"dcfy"},"gwz":"de","aw":{"wb":"fb","jj":"wzo","qa":"nx"}}},"n":{"ef":{"mq":{"ldm":"fsp","g":"mb","n":"djfeg","ln":"pf","tth":"iyyg"},"owsgl":"e","w":{"cdrk":"yyu","b":"hd","byby":"dom","myt":"ybv"},"d":{"lu":"ti","ue":"s","rhi":"b","pm":"np"}}},"k":"ahfg","qjdtb":"n","c":{"lpls":{"s":{"xkx":"e","gf":"nvr"},"zd":{"uio":"pqit","g":"k","j":"r"},"nbh":"eai","d":"hf"},"qxg":{"he":"cq","n":"ea","rw":"pn"},"utc":"zted"}},"fb":"gg"}}`,
    noOfQueries: 53,
    queries: [
      'y.fb',
      'y.gl.c.lpls.d',
      'y.gl.c.lpls.nbh',
      'y.gl.c.lpls.s.gf',
      'y.gl.c.lpls.s.xkx',
      'y.gl.c.lpls.zd.g',
      'y.gl.c.lpls.zd.j',
      'y.gl.c.lpls.zd.uio',
      'y.gl.c.qxg.he',
      'y.gl.c.qxg.n',
      'y.gl.c.qxg.rw',
      'y.gl.c.utc',
      'y.gl.k',
      'y.gl.n.ef.d.lu',
      'y.gl.n.ef.d.pm',
      'y.gl.n.ef.d.rhi',
      'y.gl.n.ef.d.ue',
      'y.gl.n.ef.mq.g',
      'y.gl.n.ef.mq.ldm',
      'y.gl.n.ef.mq.ln',
      'y.gl.n.ef.mq.n',
      'y.gl.n.ef.mq.tth',
      'y.gl.n.ef.owsgl',
      'y.gl.n.ef.w.b',
      'y.gl.n.ef.w.byby',
      'y.gl.n.ef.w.cdrk',
      'y.gl.n.ef.w.myt',
      'y.gl.qjdtb',
      'y.gl.unjv.azn.ckt',
      'y.gl.unjv.b.aw.jj',
      'y.gl.unjv.b.aw.qa',
      'y.gl.unjv.b.aw.wb',
      'y.gl.unjv.b.dxuy',
      'y.gl.unjv.b.gwz',
      'y.gl.unjv.b.gz.ayo',
      'y.gl.unjv.b.gz.kss',
      'y.gl.unjv.b.gz.qz',
      'y.gl.unjv.b.gz.vv',
      'y.gl.unjv.flv',
      'y.gl.unjv.phgv.dpqv',
      'y.gl.unjv.phgv.jkw.b',
      'y.gl.unjv.phgv.jkw.gq',
      'y.gl.unjv.phgv.jkw.hwuf',
      'y.gl.unjv.vv.khhe',
      'y.gl.unjv.vv.u.jtn',
      'y.gl.unjv.vv.u.mito',
      'y.gl.unjv.vv.u.nly',
      'y.gl.unjv.vv.vre.hx',
      'y.gl.unjv.vv.vre.kefi',
      'y.gl.unjv.vv.vre.y',
      'y.gl.unjv.vv.vu.cz',
      'y.gl.unjv.vv.vu.ebvm',
      'y.gl.unjv.vv.vu.loz',
    ],
    output:
      'gg,hf,eai,nvr,e,k,r,pqit,cq,ea,pn,zted,ahfg,ti,np,b,s,mb,fsp,pf,djfeg,iyyg,e,hd,dom,yyu,ybv,n,oft,wzo,nx,fb,rwn,de,dcfy,jxwi,cp,osos,c,luh,qzv,ivx,xrnif,gfx,gfze,nh,przd,lng,ljxc,jwewp,hp,e,xpwdd',
  },
];

useCases.forEach((useCase, index) => {
  test(`JSON parsing implementation, use case ${index + 1}`, () => {
    expect(solve(useCase.text, useCase.noOfQueries, useCase.queries)).toBe(
      useCase.output
    );
  });
});
